"""Generate a preview HTML page showing chord diagrams for inspection.

Run:
    python scripts/preview.py
    open preview.html

This script doesn't require PyScript — it bakes the SVG straight into an
HTML file we can open in any browser. It's the smoke test for the renderer
before we touch the UI.
"""

from __future__ import annotations

import sys
from pathlib import Path

# Allow running from the project root.
ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))

from chords import parse  # noqa: E402
from render import RenderOptions, render_voicing  # noqa: E402
from tunings import DADGAD, DROP_D, OPEN_D, OPEN_G, STANDARD  # noqa: E402
from voicings import find_voicings  # noqa: E402


CHORDS_STANDARD = [
    # Triads
    "C", "D", "E", "G", "A",
    "Am", "Dm", "Em",
    "F", "Bb", "B",
    # Sevenths
    "G7", "D7", "C7", "Cmaj7", "Am7", "Dm7", "Em7",
    # Extensions
    "Cadd9", "Cmaj9", "Am9", "C9",
    # Suspended
    "Dsus4", "Asus2",
    # Slash
    "D/F#", "C/E", "Am7/G",
    # Altered
    "G7b9", "C7#9", "Em7b5",
]


def render_section(title: str, voicings, chord, options=None) -> str:
    out = [f'<section><h3>{title}</h3><div class="row">']
    for v in voicings:
        out.append('<div class="voicing">')
        out.append(render_voicing(v, chord, options))
        out.append(
            f'<div class="caption">'
            f'frets: {_pretty(v.frets)} · '
            f'fingers: {v.fingers}'
            f'{" · barre " + str(v.barre[0]) + "fr" if v.barre else ""}'
            f' · score: {v.score:.2f}'
            f'</div>'
        )
        out.append('</div>')
    out.append('</div></section>')
    return "".join(out)


def _pretty(frets) -> str:
    return " ".join("x" if f is None else str(f) for f in frets)


def main() -> None:
    sections: list[str] = []

    # ---- Standard tuning, varied label modes on one chord ----
    sections.append("<h2>Label modes (Cmaj9, Standard tuning)</h2>")
    c = parse("Cmaj9")
    vs = find_voicings(c, STANDARD)[:3]
    for mode in ("fingers", "degrees", "notes", "none"):
        opts = RenderOptions(label_mode=mode)
        sections.append(render_section(f'label_mode="{mode}"', vs, c, opts))

    # ---- Standard tuning, several chords ----
    sections.append("<h2>Standard tuning (top 6 voicings each)</h2>")
    for symbol in CHORDS_STANDARD:
        c = parse(symbol)
        vs = find_voicings(c, STANDARD)
        sections.append(render_section(f"{symbol}", vs, c))

    # ---- Open tunings ----
    sections.append("<h2>Open tunings</h2>")
    for tuning, symbols in [
        (DROP_D, ["D", "G", "A", "Em"]),
        (OPEN_G, ["G", "C", "D", "Em"]),
        (OPEN_D, ["D", "G", "A"]),
        (DADGAD, ["D", "Dsus4", "G", "A"]),
    ]:
        for symbol in symbols:
            c = parse(symbol)
            vs = find_voicings(c, tuning)
            sections.append(
                render_section(f"{symbol} — {tuning.name}", vs, c)
            )

    html = f"""<!DOCTYPE html>
<html lang="fr">
<head>
<meta charset="utf-8">
<title>Chord diagram preview</title>
<style>
  body {{
    font-family: -apple-system, BlinkMacSystemFont, sans-serif;
    margin: 24px;
    background: #fafafa;
    color: #1c1c1e;
  }}
  h2 {{
    border-bottom: 2px solid #1c1c1e;
    padding-bottom: 4px;
    margin-top: 32px;
  }}
  h3 {{
    margin: 16px 0 8px;
    font-size: 14px;
    color: #444;
  }}
  section {{
    margin-bottom: 16px;
  }}
  .row {{
    display: flex;
    gap: 16px;
    flex-wrap: wrap;
  }}
  .voicing {{
    background: white;
    padding: 8px;
    border: 1px solid #ddd;
    border-radius: 6px;
  }}
  .caption {{
    text-align: center;
    font-size: 11px;
    color: #666;
    margin-top: 4px;
    font-family: ui-monospace, Menlo, monospace;
  }}
</style>
</head>
<body>
<h1>Chord diagram preview</h1>
<p>Generated by <code>scripts/preview.py</code>.</p>
{''.join(sections)}
</body>
</html>
"""

    out = ROOT / "preview.html"
    out.write_text(html, encoding="utf-8")
    print(f"Wrote {out}")


if __name__ == "__main__":
    main()
